name: project_ecommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
#  google_sign_in: ^6.1.0
#  firebase_core: ^2.10.0
#  firebase_auth: ^4.4.2
#  flutter_facebook_auth: ^5.0.9
#  flutter_login_facebook: ^1.8.0
#  cloud_firestore: ^4.6.0
#  sqflite: ^2.2.8+1
#  path: ^1.8.2
#  shared_preferences: ^2.1.0
  flutter_svg: ^1.1.6
  custom_check_box: ^0.0.4
#  another_stepper: ^1.2.2
#  image_picker: ^0.8.7+4
#  google_fonts: ^4.0.4
#  get_storage: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/


  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

  #    - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
